version: "3"
services:
  django: &django
    build:
      context: .
      dockerfile: ./base/compose/dev/django/Dockerfile
    ports:
      - "8000:8000"
      - "4444:4444"
    stdin_open: true
    tty: true
    volumes:
      - ./base/app:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
 
  db:
    build:
      context: .
      dockerfile: ./base/compose/dev/postgres/Dockerfile
    image: base_production_postgres
    env_file:
      - ./.envs/.dev/.postgres
    ports:
      - "5434:5432"
    

      
