#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py wait_for_db 
python manage.py migrate
# python /app/manage.py collectstatic --noinput
uwsgi --socket :5001 --master --enable-threads --module config.wsgi